package com.orinoco.commons.EvarSections

import com.orinoco.adapter.sessionize.cache.evar.EvarLastExCheckout
import com.orinoco.commons.EvarUtils.getEvarized
import com.orinoco.schema.cdna.CustomerDNA

object EvarLastExCheckoutUtils {
  /**
   * Objective:
   *    This script has one main purpose:
   *      1. Grab data to be evarized and apply them appropriately to the EvarLastExCheckout case class.
   **/


  def evarLastExCheckoutGrabber(evarized: Map[String, Option[Any]], cdna: CustomerDNA): EvarLastExCheckout = EvarLastExCheckout(
    abtest_l_ex_checkout = getEvarized[String]("abtest_l_ex_checkout", evarized),
    abtest_target_l_ex_checkout = getEvarized[Map[String, String]]("abtest_target_l_ex_checkout", evarized),
    acc_aid_l_ex_checkout = getEvarized[String]("acc_aid_l_ex_checkout", evarized),
    action_params_l_ex_checkout = getEvarized[Map[String, String]]("action_params_l_ex_checkout", evarized),
    actype_l_ex_checkout = getEvarized[String]("actype_l_ex_checkout", evarized),
    aflg_l_ex_checkout = getEvarized[Int]("aflg_l_ex_checkout", evarized),
    amp_l_ex_checkout = getEvarized[Boolean]("amp_l_ex_checkout", evarized),
    app_name_l_ex_checkout = getEvarized[String]("app_name_l_ex_checkout", evarized),
    app_type_l_ex_checkout = getEvarized[String]("app_type_l_ex_checkout", evarized),
    app_ver_l_ex_checkout = getEvarized[String]("app_ver_l_ex_checkout", evarized),
    area_l_ex_checkout = getEvarized[String]("area_l_ex_checkout", evarized),
    bgenre_l_ex_checkout = getEvarized[String]("bgenre_l_ex_checkout", evarized),
    bot_flag_l_ex_checkout = getEvarized[Int]("bot_flag_l_ex_checkout", evarized),
    bot_name_l_ex_checkout = getEvarized[String]("bot_name_l_ex_checkout", evarized),
    browser_app_type_l_ex_checkout = getEvarized[String]("browser_app_type_l_ex_checkout", evarized),
    browser_l_ex_checkout = getEvarized[String]("browser_l_ex_checkout", evarized),
    browser_type_l_ex_checkout = getEvarized[String]("browser_type_l_ex_checkout", evarized),
    cc_l_ex_checkout = getEvarized[String]("cc_l_ex_checkout", evarized),
    chkout_l_ex_checkout = getEvarized[Int]("chkout_l_ex_checkout", evarized),
    city_l_ex_checkout = getEvarized[String]("city_l_ex_checkout", evarized),
    cka_l_ex_checkout = getEvarized[String]("cka_l_ex_checkout", evarized),
    compid_l_ex_checkout = getEvarized[Array[String]]("compid_l_ex_checkout", evarized),
    complemented_easyid_l_ex_checkout = getEvarized[String]("complemented_easyid_l_ex_checkout", evarized),
    contents_pos_l_ex_checkout = getEvarized[Int]("contents_pos_l_ex_checkout", evarized),
    country_l_ex_checkout = getEvarized[String]("country_l_ex_checkout", evarized),
    cp_l_ex_checkout = getEvarized[Map[String, String]]("cp_l_ex_checkout", evarized),
    custom_dimension_l_ex_checkout = getEvarized[Map[String, String]]("custom_dimension_l_ex_checkout", evarized),
    cycode_l_ex_checkout = getEvarized[String]("cycode_l_ex_checkout", evarized),
    cycodelist_l_ex_checkout = getEvarized[String]("cycodelist_l_ex_checkout", evarized),
    device_l_ex_checkout = getEvarized[String]("device_l_ex_checkout", evarized),
    device_summary_l_ex_checkout = getEvarized[String]("device_summary_l_ex_checkout", evarized),
    device_type_l_ex_checkout = getEvarized[String]("device_type_l_ex_checkout", evarized),
    domain_l_ex_checkout = getEvarized[String]("domain_l_ex_checkout", evarized),
    easyid_l_ex_checkout = getEvarized[String]("easyid_l_ex_checkout", evarized),
    errors_l_ex_checkout = getEvarized[Map[String, String]]("errors_l_ex_checkout", evarized),
    esq_l_ex_checkout = getEvarized[String]("esq_l_ex_checkout", evarized),
    genre_l_ex_checkout = getEvarized[String]("genre_l_ex_checkout", evarized),
    igenre_l_ex_checkout = getEvarized[Array[String]]("igenre_l_ex_checkout", evarized),
    igenrenamepath_l_ex_checkout = getEvarized[String]("igenrenamepath_l_ex_checkout", evarized),
    igenrepath_l_ex_checkout = getEvarized[String]("igenrepath_l_ex_checkout", evarized),
    inflow_channel_acc_aid_l_ex_checkout = getEvarized[String]("inflow_channel_acc_aid_l_ex_checkout", evarized),
    inflow_channel_domain_l_ex_checkout = getEvarized[String]("inflow_channel_domain_l_ex_checkout", evarized),
    inflow_channel_entry_l_ex_checkout = getEvarized[String]("inflow_channel_entry_l_ex_checkout", evarized),
    inflow_channel_l_ex_checkout = getEvarized[String]("inflow_channel_l_ex_checkout", evarized),
    inflow_channel_page_name_l_ex_checkout = getEvarized[String]("inflow_channel_page_name_l_ex_checkout", evarized),
    inflow_channel_path_l_ex_checkout = getEvarized[String]("inflow_channel_path_l_ex_checkout", evarized),
    inflow_channel_search_word_l_ex_checkout = getEvarized[String]("inflow_channel_search_word_l_ex_checkout", evarized),
    inflow_channel_site_section_l_ex_checkout = getEvarized[String]("inflow_channel_site_section_l_ex_checkout", evarized),
    ino_l_ex_checkout = getEvarized[String]("ino_l_ex_checkout", evarized),
    ip_l_ex_checkout = getEvarized[String]("ip_l_ex_checkout", evarized),
    isaction_l_ex_checkout = getEvarized[Boolean]("isaction_l_ex_checkout", evarized),
    is_entry_l_ex_checkout = getEvarized[Boolean]("is_entry_l_ex_checkout", evarized),
    is_exit_l_ex_checkout = getEvarized[Boolean]("is_exit_l_ex_checkout", evarized),
    itag_l_ex_checkout = getEvarized[Array[String]]("itag_l_ex_checkout", evarized),
    item_genre_path_l_ex_checkout = getEvarized[String]("item_genre_path_l_ex_checkout", evarized),
    item_name_l_ex_checkout = getEvarized[String]("item_name_l_ex_checkout", evarized),
    itemid_l_ex_checkout = getEvarized[Array[String]]("itemid_l_ex_checkout", evarized),
    itemurl_l_ex_checkout = getEvarized[String]("itemurl_l_ex_checkout", evarized),
    js_user_agent_l_ex_checkout = getEvarized[String]("js_user_agent_l_ex_checkout", evarized),
    l_id_l_ex_checkout = getEvarized[String]("l_id_l_ex_checkout", evarized),
    l2id_l_ex_checkout = getEvarized[String]("l2id_l_ex_checkout", evarized),
    lang_l_ex_checkout = getEvarized[String]("lang_l_ex_checkout", evarized),
    loc_l_ex_checkout = getEvarized[Map[String, Double]]("loc_l_ex_checkout", evarized),
    lsid_l_ex_checkout = getEvarized[String]("lsid_l_ex_checkout", evarized),
    maker_l_ex_checkout = getEvarized[String]("maker_l_ex_checkout", evarized),
    media_autoplay_l_ex_checkout = getEvarized[Int]("media_autoplay_l_ex_checkout", evarized),
    media_event_l_ex_checkout = getEvarized[String]("media_event_l_ex_checkout", evarized),
    media_iframeurl_l_ex_checkout = getEvarized[String]("media_iframeurl_l_ex_checkout", evarized),
    media_name_l_ex_checkout = getEvarized[String]("media_name_l_ex_checkout", evarized),
    media_segment_l_ex_checkout = getEvarized[String]("media_segment_l_ex_checkout", evarized),
    member_l_ex_checkout = getEvarized[String]("member_l_ex_checkout", evarized),
    memberid_l_ex_checkout = getEvarized[String]("memberid_l_ex_checkout", evarized),
    mnetw_l_ex_checkout = getEvarized[Int]("mnetw_l_ex_checkout", evarized),
    model_l_ex_checkout = getEvarized[String]("model_l_ex_checkout", evarized),
    mori_l_ex_checkout = getEvarized[Int]("mori_l_ex_checkout", evarized),
    mos_l_ex_checkout = getEvarized[String]("mos_l_ex_checkout", evarized),
    navigation_genre_path_l_ex_checkout = getEvarized[String]("navigation_genre_path_l_ex_checkout", evarized),
    navtype_l_ex_checkout = getEvarized[Int]("navtype_l_ex_checkout", evarized),
    oa_l_ex_checkout = getEvarized[String]("oa_l_ex_checkout", evarized),
    operating_system_l_ex_checkout = getEvarized[String]("operating_system_l_ex_checkout", evarized),
    operating_system_type_l_ex_checkout = getEvarized[String]("operating_system_type_l_ex_checkout", evarized),
    order_id_l_ex_checkout = getEvarized[String]("order_id_l_ex_checkout", evarized),
    order_list_l_ex_checkout = getEvarized[Array[String]]("order_list_l_ex_checkout", evarized),
    path_l_ex_checkout = getEvarized[String]("path_l_ex_checkout", evarized),
    path_level1_l_ex_checkout = getEvarized[String]("path_level1_l_ex_checkout", evarized),
    path_level2_l_ex_checkout = getEvarized[String]("path_level2_l_ex_checkout", evarized),
    path_level3_l_ex_checkout = getEvarized[String]("path_level3_l_ex_checkout", evarized),
    path_level4_l_ex_checkout = getEvarized[String]("path_level4_l_ex_checkout", evarized),
    path_level5_l_ex_checkout = getEvarized[String]("path_level5_l_ex_checkout", evarized),
    payment_l_ex_checkout = getEvarized[String]("payment_l_ex_checkout", evarized),
    pgl_l_ex_checkout = getEvarized[String]("pgl_l_ex_checkout", evarized),
    pgn_l_ex_checkout = getEvarized[String]("pgn_l_ex_checkout", evarized),
    pgt_l_ex_checkout = getEvarized[String]("pgt_l_ex_checkout", evarized),
    prdctcd_l_ex_checkout = getEvarized[String]("prdctcd_l_ex_checkout", evarized),
    previous_acc_aid_l_ex_checkout = getEvarized[String]("previous_acc_aid_l_ex_checkout", evarized),
    previous_domain_l_ex_checkout = getEvarized[String]("previous_domain_l_ex_checkout", evarized),
    previous_page_name_l_ex_checkout = getEvarized[String]("previous_page_name_l_ex_checkout", evarized),
    previous_path_l_ex_checkout = getEvarized[String]("previous_path_l_ex_checkout", evarized),
    previous_service_group_l_ex_checkout = getEvarized[String]("previous_service_group_l_ex_checkout", evarized),
    previous_site_section_l_ex_checkout = getEvarized[String]("previous_site_section_l_ex_checkout", evarized),
    price_l_ex_checkout = getEvarized[Array[Double]]("price_l_ex_checkout", evarized),
    publisher_l_ex_checkout = getEvarized[String]("publisher_l_ex_checkout", evarized),
    rancode_l_ex_checkout = getEvarized[String]("rancode_l_ex_checkout", evarized),
    rat_device_code_l_ex_checkout = getEvarized[String]("rat_device_code_l_ex_checkout", evarized),
    recent_prchs_code_l_ex_checkout = cdna.recent_prchs_code,
    recent_prchs_date_l_ex_checkout = cdna.recent_prchs_date,
    ref_l_ex_checkout = getEvarized[String]("ref_l_ex_checkout", evarized),
    referrer_domain_l_ex_checkout = getEvarized[String]("referrer_domain_l_ex_checkout", evarized),
    referrer_summary_l_ex_checkout = getEvarized[String]("referrer_summary_l_ex_checkout", evarized),
    referrer_type_l_ex_checkout = getEvarized[String]("referrer_type_l_ex_checkout", evarized),
    res_l_ex_checkout = getEvarized[String]("res_l_ex_checkout", evarized),
    resdate_l_ex_checkout = getEvarized[String]("resdate_l_ex_checkout", evarized),
    reservation_id_l_ex_checkout = getEvarized[String]("reservation_id_l_ex_checkout", evarized),
    reslayout_l_ex_checkout = getEvarized[String]("reslayout_l_ex_checkout", evarized),
    rg_books_l_ex_checkout = getEvarized[Int]("rg_books_l_ex_checkout", evarized),
    rg_kobo_l_ex_checkout = getEvarized[Int]("rg_kobo_l_ex_checkout", evarized),
    s_id_l_ex_checkout = getEvarized[String]("s_id_l_ex_checkout", evarized),
    sc2id_l_ex_checkout = getEvarized[String]("sc2id_l_ex_checkout", evarized),
    scid_l_ex_checkout = getEvarized[String]("scid_l_ex_checkout", evarized),
    search_word_external_l_ex_checkout = getEvarized[String]("search_word_external_l_ex_checkout", evarized),
    service_category_l_ex_checkout = getEvarized[String]("service_category_l_ex_checkout", evarized),
    service_group_l_ex_checkout = getEvarized[String]("service_group_l_ex_checkout", evarized),
    service_type_l_ex_checkout = getEvarized[String]("service_type_l_ex_checkout", evarized),
    sgenre_l_ex_checkout = getEvarized[String]("sgenre_l_ex_checkout", evarized),
    shopid_l_ex_checkout = getEvarized[String]("shopid_l_ex_checkout", evarized),
    shopid_itemid_l_ex_checkout = getEvarized[Array[String]]("shopid_itemid_l_ex_checkout", evarized),
    shopidlist_l_ex_checkout = getEvarized[Array[String]]("shopidlist_l_ex_checkout", evarized),
    shopurl_l_ex_checkout = getEvarized[String]("shopurl_l_ex_checkout", evarized),
    shopurllist_l_ex_checkout = getEvarized[String]("shopurllist_l_ex_checkout", evarized),
    sq_l_ex_checkout = getEvarized[String]("sq_l_ex_checkout", evarized),
    srt_l_ex_checkout = getEvarized[String]("srt_l_ex_checkout", evarized),
    ssc_l_ex_checkout = getEvarized[String]("ssc_l_ex_checkout", evarized),
    tag_l_ex_checkout = getEvarized[Array[String]]("tag_l_ex_checkout", evarized),
    target_ele_l_ex_checkout = getEvarized[String]("target_ele_l_ex_checkout", evarized),
    ua_l_ex_checkout = getEvarized[String]("ua_l_ex_checkout", evarized),
    url_l_ex_checkout = getEvarized[String]("url_l_ex_checkout", evarized),
    user_age_l_ex_checkout = cdna.user_age,
    user_category_by_recent_prchs_l_ex_checkout = cdna.user_category_by_recent_prchs,
    user_city_l_ex_checkout = cdna.user_city,
    user_gender_l_ex_checkout = cdna.user_gender,
    user_rank_l_ex_checkout = cdna.user_rank,
    ver_l_ex_checkout = getEvarized[String]("ver_l_ex_checkout", evarized),
    zero_hit_search_word_l_ex_checkout = getEvarized[String]("zero_hit_search_word_l_ex_checkout", evarized)
  )
}